### PR TITLE
Fixes #12-animated image showing completion on an xml file …

### LINKED ISSUE #12: Provide animated image showing completion on an xml file in the readme

### PR DESCRIPTION
**Pull request by Navyashree0923**
…in the readme.

### CODE REVIEW

**Review by apupier — CHANGES_REQUESTED** [review]
Vim has a different way of working with auto-completion than most other editors. See https://unix.stackexchange.com/questions/162528/select-an-item-in-vim-autocomplete-list-without-inserting-line-break to accept an auto-completion without having a new line inserted.
I think this will be better to provided the animated gif without the new line inserted. it will shorten the demo and go to the point more directly.

The important part is the completion for the Camel URI. Showing that normal xml completion is working was a good idea. Maybe just show one of it (just the encoding maybe and not the version) to keep the demo more focused.

**Comment by Navyashree0923** [comment]
I have updated the file, please review it @apupier

**Review by Navyashree0923 — COMMENTED** [review]
Thank you, I have updated the code

**Review by apupier — APPROVED** [review]

**Comment by apupier** [comment]
given that there isn't the keywords `fixes #12` in the commit message you will need to close the issue #12 manually

**Pull request merged**
